boostorg/url

include/boost/url/detail/config.hpp
include/boost/url/detail/impl/normalize.ipp
include/boost/url/detail/impl/remove_dot_segments.ipp
include/boost/url/detail/normalize.hpp
include/boost/url/detail/remove_dot_segments.hpp
include/boost/url/impl/url_view.ipp
include/boost/url/url.hpp
include/boost/url/url_view.hpp
test/unit/url.cpp

hash support

---

include/boost/url/impl/url.ipp
test/unit/segments.cpp
test/unit/url.cpp

fix edit_segments suffix

---

include/boost/url/grammar/parse.hpp
include/boost/url/ipv6_address.hpp
include/boost/url/params_encoded.hpp
include/boost/url/url.hpp
include/boost/url/url_view.hpp

missing url javadoc

---

doc/javadoc.hpp
doc/qbk/2.0.quicklook.qbk
doc/qbk/3.0.parsing.qbk
doc/qbk/4.0.modifying.qbk
include/boost/url/url_view.hpp
test/unit/snippets.cpp

fix #190, fix #189, fix #186, fix #185, fix #194
This PR synthesizes all suggestions mentioned in these issues.

improve examples

---

doc/qbk/0.main.qbk
doc/qbk/3.0.parsing.qbk

improve parsing docs

---

doc/qbk/1.0.overview.qbk

boost minimum requirements

---

doc/qbk/1.0.overview.qbk

release documentation

---

doc/qbk/2.0.quicklook.qbk
include/boost/url/params_encoded_view.hpp
include/boost/url/static_pool.hpp
test/unit/snippets.cpp

fix static_pool reference rendering 

---

doc/qbk/3.1.scheme.qbk

fix mailto resource type

---

include/boost/url/authority_view.hpp
include/boost/url/impl/authority_view.ipp
include/boost/url/impl/ipv4_address.ipp
include/boost/url/impl/ipv6_address.ipp
include/boost/url/impl/segments_encoded_view.ipp
include/boost/url/impl/segments_view.ipp
include/boost/url/impl/url.ipp
include/boost/url/impl/url_view.ipp
include/boost/url/ipv4_address.hpp
include/boost/url/ipv6_address.hpp
include/boost/url/segments_encoded_view.hpp
include/boost/url/segments_view.hpp
include/boost/url/url.hpp
include/boost/url/url_view.hpp

ops as hidden friends

---

include/boost/url/grammar/impl/range_rule.hpp
include/boost/url/grammar/range_rule.hpp

Silence strict-aliasing warning

---

include/boost/url/authority_view.hpp
include/boost/url/grammar/impl/unsigned_rule.hpp
include/boost/url/ipv4_address.hpp
include/boost/url/ipv6_address.hpp
include/boost/url/pct_encoded_view.hpp
include/boost/url/segments_encoded_view.hpp
include/boost/url/segments_view.hpp

Fix pointer calc in unsigned_dec_rule

---

doc/qbk/3.4.path.qbk
test/unit/doc_container.cpp

Path tests

---

include/boost/url/detail/config.hpp
include/boost/url/detail/except.hpp
include/boost/url/detail/impl/segments_iterator_impl.ipp
include/boost/url/grammar/impl/range_rule.hpp
include/boost/url/impl/authority_view.ipp
include/boost/url/impl/ipv4_address.ipp
include/boost/url/impl/ipv6_address.ipp
include/boost/url/impl/pct_string_view.ipp
include/boost/url/impl/static_url.ipp
include/boost/url/impl/url.ipp
include/boost/url/impl/url_base.ipp
include/boost/url/impl/url_view.ipp
include/boost/url/rfc/impl/ipv6_address_rule.ipp
test/unit/ipv4_address.cpp
test/unit/ipv6_address.cpp

source location option

---

include/boost/url/detail/parts_base.hpp
include/boost/url/impl/url_base.ipp
include/boost/url/url.natvis
test/unit/segments_encoded_ref.cpp
test/unit/segments_ref.cpp
test/unit/url.cpp

authority can have empty path

---

doc/Jamfile
include/boost/url/decode_view.hpp
include/boost/url/detail/config.hpp

remove BOOST_URL_PCT_STRING_VIEW

---

include/boost/url/grammar/ci_string.hpp

add comments to ci_equal

---

example/magnet/magnet.cpp

use conventions in magnet example

---

extra/test_suite.hpp
include/boost/url/detail/any_segments_iter.hpp
include/boost/url/detail/impl/any_segments_iter.ipp
include/boost/url/impl/url_base.ipp
include/boost/url/rfc/detail/charsets.hpp
include/boost/url/url_base.hpp
test/unit/doc_3_urls.cpp
test/unit/segments_encoded_ref.cpp
test/unit/segments_ref.cpp
test/unit/url.cpp
test/unit/url_base.cpp

remove_scheme encodes colons

---

include/boost/url/rfc/impl/query_rule.ipp
test/unit/doc_3_urls.cpp
test/unit/url.cpp

allow escaped null in urls

---

example/CMakeLists.txt
example/Jamfile
example/suffix_list/CMakeLists.txt
example/suffix_list/Jamfile
example/suffix_list/public_suffix_list.dat
example/suffix_list/suffix_list.cpp

suffix list example

---

doc/javadoc.hpp
doc/qbk/3.7.percent-encoding.qbk

refactor documentation typo

---

include/boost/url/params_ref.hpp
test/unit/snippets.cpp

documentation snippets

---

test/unit/parse.cpp

test tildes in query

---

doc/qbk/1.0.overview.qbk
meta/explicit-failures-markup.xml

update test matrix toolsets

---

include/boost/url/impl/url_base.ipp
include/boost/url/url_base.hpp
test/unit/url.cpp

resolve docs includes error condition

---

doc/qbk/2.0.quicklook.qbk

update quicklook snippets

---

README.md
doc/qbk/1.0.overview.qbk

remove fuzzing from docs

---

.drone.star
extra/test_suite.hpp
include/boost/url/detail/config.hpp
include/boost/url/detail/normalize.hpp
include/boost/url/impl/authority_view.ipp
include/boost/url/impl/url_view_base.ipp
include/boost/url/ipv6_address.hpp
test/Jamfile
test/unit/Jamfile
test/unit/grammar/range_rule.cpp
test/unit/ipv6_address.cpp
test/unit/url_view.cpp

test 32-bit MSVC builds

---

.github/workflows/ci.yml
doc/qbk/2.0.quicklook.qbk
test/Jamfile
test/unit/snippets.cpp

decode_view snippets

---

extra/test_main.cpp
extra/test_suite.hpp
include/boost/url/detail/any_segments_iter.hpp
include/boost/url/grammar/impl/error.ipp
include/boost/url/grammar/string_token.hpp
include/boost/url/impl/error.ipp
include/boost/url/url_base.hpp
test/Jamfile

enable pedantic warnings in tests

---

include/boost/url/rfc/detail/impl/hier_part_rule.ipp
test/unit/url_view.cpp

refactor hier_part_rule abs path

---

.drone.star
.drone/drone.sh

This PR defines a function to generate drone jobs given matching requirements with the supported combinations of compilers and standards.
(Work in progress)

drone generator

---

include/boost/url/url_view_base.hpp

fix typo in buffer javadoc

---

README.md
test/unit/snippets.cpp

update readme snippet

---

include/boost/url/detail/impl/normalize.ipp
test/unit/url.cpp

refactor segments compare function

---

include/boost/url/parse.hpp
include/boost/url/rfc/detail/relative_part_rule.hpp
include/boost/url/url_base.hpp

fix broken links in docs

---

include/boost/url/impl/url_base.ipp
include/boost/url/url.hpp
include/boost/url/url_base.hpp
test/unit/url_base.cpp

set_params convenience function

---

include/boost/url/authority_view.hpp
test/unit/authority_view.cpp

typo in authority_view javadoc

---

include/boost/url/rfc/detail/impl/hier_part_rule.ipp
test/unit/format.cpp
test/unit/parse.cpp

path-rootless considers invalid segments

---

include/boost/url/rfc/detail/impl/port_rule.ipp
test/unit/url_view.cpp

port number is defined

---

include/boost/url/grammar/detail/impl/recycled.ipp
include/boost/url/grammar/detail/recycled.hpp

Use __debugbreak (#671)

---

example/router/router.cpp

fix router warnings

---

include/boost/url/grammar/string_token.hpp
test/unit/segments_base.cpp
test/unit/segments_encoded_base.cpp

remove string_token unused include

---

.drone.star
test/Jamfile

generator creates asan jobs for macos

---

include/boost/url/grammar/impl/error.hpp
include/boost/url/grammar/impl/error.ipp
include/boost/url/impl/error.hpp
include/boost/url/impl/error.ipp

error_category best practices:

---

include/boost/url/grammar/impl/range_rule.hpp

grammar::range::iterator operator parameters by reference

---

.drone.star
.drone/drone.sh
example/finicky/finicky.cpp
example/mailto/rfc.hpp
include/boost/url/decode_view.hpp
include/boost/url/detail/any_segments_iter.hpp
include/boost/url/detail/impl/pattern.ipp
include/boost/url/detail/optional_string.hpp
include/boost/url/detail/string_view.hpp
include/boost/url/grammar/impl/string_view_base.ipp
include/boost/url/grammar/string_view_base.hpp
include/boost/url/pct_string_view.hpp
include/boost/url/string_view.hpp
include/boost/url/url_view.hpp
test/unit/format.cpp
test/unit/segments_encoded_ref.cpp

detail::to_string_view

---

.drone/drone.sh

The drone files were originally auto-generated from travis ci and there are many variables such as "TRAVIS_BRANCH". Removing those.

Remove TRAVIS in drone.sh

---

doc/qbk/quickref.xml

parse_query in reference page

---

test/unit/url.cpp

test: fluent API

---

.github/workflows/ci.yml
build/Jamfile
src/detail/url_impl.cpp
test/Jamfile

#761 rebased on top of develop and fixing any errors left

ci: self-hosted runners

---

include/boost/url/detail/normalize.hpp
include/boost/url/url_base.hpp
src/detail/normalize.cpp
test/unit/url.cpp

fix: resolve abnormal hrefs

---

example/sanitize/sanitize.cpp

fix(sanitize): extract authority

---

.github/workflows/ci.yml

ci: add GHA codecov token

---

doc/Jamfile
include/boost/url/url_base.hpp
src/detail/pattern.hpp

docs: remove detail::pattern from reference

---

.drone.star
.drone/drone.sh
doc/local-playbook.yml
doc/package-lock.json
doc/package.json
example/finicky/finicky.cpp
include/boost/url/error_types.hpp
include/boost/url/grammar/variant_rule.hpp
include/boost/url/static_url.hpp
include/boost/url/url.hpp
include/boost/url/url_base.hpp
src/url_base.cpp
test/Jamfile
test/extra/CMakeLists.txt
test/fuzz/CMakeLists.txt
test/limits/CMakeLists.txt
test/unit/CMakeLists.txt

This PR fixes a number of smaller issues that accumulated over time.

Minor issues

---

.github/workflows/ci.yml
doc/local-playbook.yml
doc/package-lock.json
doc/package.json

- Use cppalliance Antora extensions
- Update their versions
- Test MrDocs extension on different platforms

Update Antora extensions

---

doc/modules/ROOT/pages/grammar/rfc3986.adoc
doc/modules/ROOT/pages/grammar/rules.adoc
doc/modules/ROOT/pages/urls/formatting.adoc
doc/modules/ROOT/pages/urls/index.adoc
doc/modules/ROOT/pages/urls/params.adoc
doc/modules/ROOT/pages/urls/percent-encoding.adoc
doc/modules/ROOT/pages/urls/segments.adoc
include/boost/url/url_base.hpp
src/url_base.cpp
test/unit/url.cpp

docs: functions that cannot round-trip
