doc/qbk/0.main.qbk, doc/qbk/4.0.grammars.qbk, include/boost/url/grammar/parse.hpp
This PR
- fixes a number doxygen warnings and errors
- simplifies the documentation so that docca generates better output
- removes any commands docca cannot render
- includes an exposition for the grammar rule objects
- simplifies the examples
- adjusts the documentation to refer to the grammar namespace
- simplifies descriptions by removing unnecessary and excessive mathematical symbolism
- removes details that are implied from the exposition
- updates parameters to use stock sentences
- removes BOOST_URL_DOCS from overloads and adjusts documentation accordingly
=> Improve parse javadocs

CMakeLists.txt, doc/qbk/quickref.xml, include/boost/url/any_allocator.hpp, include/boost/url/detail/any_allocator.hpp, include/boost/url/detail/type_id.hpp, include/boost/url/impl/any_allocator.hpp, test/unit/CMakeLists.txt, test/unit/Jamfile, test/unit/any_allocator.cpp
A type-erased allocator with shared ownership that satisfies the requirements for Allocator.
=> add any_allocator

doc/qbk/3.0.parsing.qbk, include/boost/url/authority_view.hpp, include/boost/url/impl/authority_view.ipp, include/boost/url/impl/url_view.ipp, include/boost/url/url_view.hpp, test/unit/authority_view.cpp, test/unit/snippets.cpp, test/unit/url_view.cpp
fix #208
BREAKING CHANGE: The function url_view::collect is now called url_view::persist
=> rename collect to persist 

include/boost/url/authority_view.hpp, include/boost/url/detail/impl/any_path_iter.ipp, include/boost/url/detail/impl/any_query_iter.ipp, include/boost/url/impl/pct_encoded_view.ipp, include/boost/url/impl/pct_encoding.hpp, include/boost/url/impl/pct_encoding.ipp, include/boost/url/impl/url.ipp, include/boost/url/pct_encoding.hpp, include/boost/url/url_view.hpp, test/unit/pct_encoding.cpp
fix #230
This PR fixes the issue with the default parameters for pct encoding algorithms and updates the API according to the other recommendations in #230 
It would be good to have a good look at this because this has an impact at many other points of the library.
I'm still not sure what to do about the recommendation "add `pct_encode_append_to` and `pct_encode_assign_to`" because the functions `append` and `assign` depend on iterators which don't exist in that context:
- If the intention is to reuse the MutableString concept, the first alternative would be to create a whole new view class representing the opposite of `pct_encoded_view` (received decoded strings as input and outputing encoded strings) so we have iterators to provide `append` and `assign`. 
- If the intention is really to …
=> update pct encoding API

doc/qbk/quickref.xml, include/boost/url/detail/impl/segments_encoded_iterator_impl.ipp, include/boost/url/detail/impl/segments_iterator_impl.ipp, include/boost/url/grammar/impl/range.hpp, include/boost/url/grammar/range.hpp, include/boost/url/rfc/detail/path_increment.hpp, include/boost/url/rfc/impl/paths_rule.ipp, include/boost/url/rfc/impl/query_rule.ipp, include/boost/url/rfc/paths_rule.hpp, include/boost/url/rfc/query_rule.hpp
Instead of awkward function pointers we just store the begin and increment rules directly. Furthermore, if the small buffer size is insufficient, a dynamic allocation is performed. This allocation is based on the size of the rules, not the size of the range. None of the rules in the library currently exceed the small buffer size.
=> Refactor range

.codecov.yml
Let's test the codecov threshold setting. According to the documentation "this allows a x% drop from the previous base commit coverage".
=> Adjust codecov threshold

.github/workflows/ci.yml
The PR fixes the GHA tests that broke at daf605409a694217b96c27ebc3d33a1a76b8f82c
It's a single line of code.
=> build boost_url_extra

include/boost/url/authority_view.hpp, include/boost/url/impl/authority_view.ipp, include/boost/url/impl/url_view_base.ipp, test/unit/url.cpp
This PR simplifies the URL comparison function. It also fixes a bug where the difference between some absent and empty components was not considered. This fix was part of #425, which is now obsoleted.
=> comparison differentiates absent and empty components

.drone.star
- Upgrade s390x version, which is required so that beast will pass the tests.   
@alandefreitas questions: 
- Could examples be provided for all the sorts of formats parse_semver_range() takes?  This example is clear 'gcc >=4.8', but is there something like '11 >= gcc >= 4.8' which restricts both ends of the range?   
- The code for parse_semver_range() mentions "=" and "^".  When I set a range to just "=11" or "^11", that didn't work. Should it?
- The function seems to have "||" as a delimiter.  Does that signify logical "or"?   Should logical and "&&"  be included too?  What is an example of a range using "||" and does it generate the expected jobs?
=> Drone: modify generate function

include/boost/url/url_view.hpp, include/boost/url/url_view_base.hpp, test/unit/url_view.cpp
=> string constructors and conversions are implicit

.drone.star, include/boost/url/grammar/detail/impl/recycled.ipp, include/boost/url/grammar/detail/recycled.hpp, include/boost/url/grammar/impl/recycled.hpp, include/boost/url/grammar/recycled.hpp
=> support BOOST_URL_DISABLE_THREADS

include/boost/url/impl/error.hpp, include/boost/url/impl/error.ipp
This replicates how http-proto does error codes: 
https://github.com/CPPAlliance/http_proto/commit/dc7d2730b8d5cc5fba1d4900459eb9467289bdfc
=> make_error_code is constexpr

include/boost/url/detail/impl/any_segments_iter.ipp, test/unit/segments_encoded_ref.cpp, test/unit/url.cpp
This PR fixes the first issue in https://github.com/boostorg/url/issues/674
`path_iter` was identifying `"/"` as having `fast_nseg == 1` while it should be `0` according to the library convention that `"/"` represents `{}`  and `"/./"` represents `{""}`.
This led to counterintuitive results like:
```cpp
assert(url("/").set_path("/").buffer() == "/./");
```
A second problem with this convention is that when we normalize a path from `"/./"` to its equivalent `"/"`, the segments representation goes from `{""}` to `{}`, but there's nothing we can or should do about that.
=> path_iter "/" is fast_nseg zero

include/boost/url/impl/url_base.ipp, test/unit/url.cpp
fix #674
This PR fixes the second issue in https://github.com/boostorg/url/issues/674
It was also a failure to handle an exception from the general case related to our convention that `"/"` -> `{}` and `"/./"` -> `{""}`. This caused unexpected `set_path` to have unexpected results.
=> path normalization updates parameters

.drone.star, .drone/drone.sh
A proposed change to the caching methodology.
The cache key has been the boostorg/boost commit SHA, which changes around every 4 hours and thus invalidates the cache most of the times you attempt to use it. If a few hours have passed and there is a pull request or a commit, those will be cache misses.
The new strategy is to basically always use the cache. 
common_install.sh runs every time. "git pull" or "submodule update" only take a few seconds because they don't need to download a full git repository. b2 recompilation will be skipped.
=> Update drone caching strategy

.github/actions/b2_workflow/action.yml
@alandefreitas, a suggestion to remove the 'ilammy/msvc-dev-cmd@v1' action.     
The reasons are:
- it's not required for the CI jobs to build.
- b2 is smart enough to find a compiler anyway.
- when debugging gha runners, and jobs were failing, it actually became a question: "Is the ilammy/msvc-dev-cmd action involved in this crash, or it's not?"   (The latest evidence is, probably not. But still - fewer steps is better.)
=> Github Actions: remove ilammy/msvc-dev-cmd

test/unit/url_base.cpp
Although the issue has been fixed since 3a237c35, this commit includes the test from #755.
closes #755
=> test: IPv4-address leftover forms hostname

CMakeLists.txt, src/parse_query.cpp, test/unit/parse_query.cpp
Although c518dbaa already included BOOST_SRC_DIR and removed support for standalone installation, this PR enforces that appropriate BOOST_INCLUDE_LIBRARIES are set according to the build options.
fix #679
=> build: enforce BOOST_SRC_DIR

include/boost/url/url_view.hpp, test/unit/url_view.cpp
=> fix: url_view string_view constructor requires non-url_view_base

.drone/drone.sh
Drone caching had been disabled in 20ab896f because of an issue in boostorg/boost-ci. Since then, this issue has been fixed in boostorg/boost-ci PR #213.
closes #760
=> ci: enable drone caching

include/boost/url/rfc/detail/ipv6_addrz_rule.hpp, include/boost/url/url_view_base.hpp, src/rfc/detail/ip_literal_rule.cpp, src/rfc/detail/ipv6_addrz_rule.cpp, src/url_view_base.cpp, test/unit/ipv6_address.cpp, test/unit/url_view.cpp
This commit changes the IP-literal rule to also accept IPv6addrz as a valid ipv6 host type. IPv6addrz includes a ZoneID at the end, delimited by an encoded "%25". The ipv6_address class is unmodified, as the mapping from the ZoneID to a std::uint32_t is dependent on the application context. The original ZoneID can be obtained from the url_view.
fix #711
=> fix: IP-literal can be IPv6addrz

doc/qbk/0.main.qbk, doc/qbk/quickref.xml, include/boost/url/authority_view.hpp, include/boost/url/decode_view.hpp, include/boost/url/error_types.hpp, include/boost/url/grammar/delim_rule.hpp, include/boost/url/grammar/variant_rule.hpp, include/boost/url/optional.hpp, include/boost/url/param.hpp, include/boost/url/pct_string_view.hpp, include/boost/url/url.hpp, include/boost/url/url_base.hpp, include/boost/url/url_view.hpp
This PR fixes issues that were causing warnings when generating the reference with docca. Along with other fixes recently pushed in `boostorg/docca`, it should completely fix all problems related to the reference.
- 2e0c3eec) docs: update javadoc deprecated references: This commit fixes a mistake where the javadoc for many deprecated aliases included references to the deprecated alias `boost::core::string_view` instead of the correct deprecated aliases `boost::optional`, `system::error_category`, `system::error_code`, `system::error_condition`, `system::system_error`, and `system::result`.
- 3ded066a) docs: remove references to variant: This commit removes links and references to 'variant' in both the .qbk and .xml files under the documentation directory. These references were removed as …
=> docs: fix reference issues

extra/gdb/README.adoc, extra/gdb/__init__.py, extra/gdb/boost_url_printers.py
I have slowly developed these pretty printers over time as I needed help debugging the most complex details of Boost.Url (in other words, there was no extra work involved in this). They can now complement the Boost.Url natvis file already provided by the library.
To use the printers, users can create or modify their `.gdbinit` file to contain the following:
```python
python
import sys
sys.path.insert(0, '/path/to/boost/url/extra/gdb')
from boost_url_printers import register_boost_url_printers
register_boost_url_printers()
end
```
(This is all documented)
so that in
```cpp
auto r = parse_uri("https://username:password@example.com:8080/path/to/resource?query_param=value#section");
```
this
becomes
This could save users a lot of time trying to figure out why a string parsed but the result of …
=> style: GDB printers

example/file_router/file_router.cpp
On Windows, fs::path::c_str() returns wchar_t const* so cannot be streamed to std::cout. fs::path is output streamable anyway (it might quote it, but that should be fine).
=> Fix Windows build of file_router example

test/CMakeLists.txt
I am building Boost using CMake along with the Intel C++ compiler. I was seeing this error at configuration time:
```
-- Performing Test BOOST_STACKTRACE_HAS_WINDBG - Failed
-- Performing Test BOOST_STACKTRACE_HAS_WINDBG_CACHED
-- Performing Test BOOST_STACKTRACE_HAS_WINDBG_CACHED - Failed
-- Boost.Stacktrace: noop ON, backtrace OFF, addr2line ON, basic ON, windbg OFF, windbg_cached OFF
-- Boost.Thread: threading API is pthread
CMake Error at libs/url/test/unit/CMakeLists.txt:19 (set_source_files_properties):
set_source_files_properties called with incorrect number of arguments.
CMake Error at libs/url/test/limits/CMakeLists.txt:19 (set_source_files_properties):
set_source_files_properties called with incorrect number of arguments.
-- Configuring incomplete, errors occurred!
See also …
```
=> test: fix CMake issue with unusual compilers

.github/workflows/ci.yml, CMakeLists.txt, test/cmake_test/CMakeLists.txt, test/cmake_test/main.cpp
The updated CI workflows include building Boost.URL with the Boost super-project as the project root, with Boost.URL as the project root, building a project that adds the Boost super-project as a subdirectory, a project that adds Boost.URL as a subdirectory, that finds Boost as a package and that finds Boost.URL as a package. The PR also updates cpp-actions to its version v1.6.0, which handles more recent versions of clang.
fix #796
=> ci: test all Boost workflows

.github/workflows/ci.yml
This PR simplifies the test steps by aggregating common parameters for the cmake workflows. To achieve that, all cmake related actions have been ported to JavaScript, which has better support, provides more features, and is easier to maintain. A lot of bugs were fixed in the process.
=> ci: aggregate integration test parameters

include/boost/url/rfc/detail/charsets.hpp, test/unit/url_base.cpp, test/unit/url_view.cpp
Although 1317ca8c includes support for brackets in key_chars, the lack of support in query_chars made still led to errors when the the complete url is parsed at once.
fix #93
=> fix: handle brackets in query_chars

.github/workflows/ci.yml, test/unit/format.cpp
This PR includes "latest" in the list of cxxstd versions used by b2. 
It also includes a fix to tests that broke in more recent versions of MSVC with the "latest" option.
=> ci(b2-workflow): cxxstd include latest

include/boost/url/grammar/range_rule.hpp
=> docs: range::operator= is assignment

.github/workflows/ci.yml
Use the same process as boost-ci to generate and upload coverage. It generates an all.info file with information about all boost libraries and filters the files in */libs/url/*. This fixes a problem with the --include pattern we used to use.
fix #821
=> ci: extract url coverage from all

include/boost/url/detail/encode.hpp, src/detail/any_params_iter.cpp, src/detail/any_segments_iter.cpp, src/url_base.cpp
The private unsafe encoding functions received a parameter to determine the encoding options. However, these functions are never used in any context where these options should diverge from the default values.
This is a partial solution to https://github.com/boostorg/url/issues/828, where `detail/encode.hpp` is the file with the lowest coverage.
=> refactor: unsafe encoding assumes default options 

include/boost/url/static_url.hpp, src/static_url.cpp, test/unit/static_url.cpp
This commit includes tests for the url_base functions whose behavior is customized by static_url.
This is a partial solution to #828, where static_url.cpp has low coverage.
=> test: static_url url_base functions

src/authority_view.cpp, test/unit/authority_view.cpp
This commit includes tests for the authority_view host functions when the host type is invalid.
This is a partial solution to #828, where authority_view.cpp has low coverage.
=> test: authority_view host functions

src/detail/decode.cpp
This commit simplifies duplicated code so that we tests all paths for the pct_string_view::decode function. Unreachable paths are also marked.
This is a partial solution to #828, where src/detail/decode.cpp has low coverage.
=> test: cover pct_string_view::decode

src/grammar/detail/recycled.cpp, test/unit/grammar/recycled.cpp
This commit includes tests for shared `recycled_ptr`s. Unreachable paths are also marked.
This is the last in a series of commits that intend to fix #828, where `recycled_ptr` had low coverage.
fix #828
=> test: shared recycled_ptrs

doc/generate-files.mjs
This is to solve a case where selfDir is not literally "url" but might be "url-docs" or similar. Which is why the `${selfDir}` variable was added, to start with.
=> Antora docs: modify dir copy step

src/segments_view.cpp
=> workaround for craypp crash

.github/workflows/ci.yml, extra/test_suite.hpp, test/unit/natvis.cpp
This PR fixes all CI problems related to GHA upgrading to node 20. It also updates the matrix to include the latest compilers.
=> ci: node20 actions

.github/workflows/ci.yml, doc/generate-files.mjs, doc/modules/ROOT/examples/unit/snippets.cpp, doc/modules/ROOT/pages/urls/stringtoken.adoc, doc/qbk/0.main.qbk, doc/qbk/3.6.stringtoken.qbk, test/unit/snippets.cpp
=> docs: string_token exposition

doc/lib/cpp.js, doc/modules/ROOT/pages/concepts/Rule.adoc, doc/package-lock.json, doc/package.json
This PR replaces xmldom with fast-xml-parser and adds support for more kinds of symbols.
xmldom hasn't been receiving maintenance and has known security vulnerabilities: https://github.com/boostorg/url/security/dependabot/3
The code was also refactored to support multiple ways to compose symbols (fundamental types, namespaces, search in namespaces in the tag file, template parameters, filenames, and nested classes). For instance,
```adoc
cpp:std[]
cpp:bool[]
cpp:std::string_view[]
cpp:std::string_view[]
cpp:std::FILE[]
cpp:std::vector[]
cpp:std::vector<int>[]
cpp:std::vector<std::vector<int>,std::allocator<int>>[]
cpp:MyClass<int,std::vector<double>,std::map<int,std::string>>[]
cpp:std::vector<std::vector<int>,std::allocator<int>>::const_iterator[]
cpp:"algorithm"[]
cpp:<algorithm>[] …
```
=> docs: cpp.js uses fast-xml-parser

CMakeLists.txt, doc/antora.yml, doc/build_antora.sh, doc/local-playbook.yml, doc/package-lock.json, doc/package.json
This completes the transition of all Antora extensions.
=> docs: cpp-reference extension is npm package

src/detail/move_chars.hpp
=> Removed unused variable

.github/workflows/ci.yml, doc/local-playbook.yml, doc/modules/ROOT/pages/urls/params.adoc, include/boost/url/grammar/impl/variant_rule.hpp, src/rfc/absolute_uri_rule.cpp, src/rfc/detail/query_part_rule.hpp, src/rfc/origin_form_rule.cpp, src/rfc/query_rule.cpp, src/rfc/relative_ref_rule.cpp, src/rfc/uri_rule.cpp, test/cmake_test/main.cpp, test/unit/grammar/variant_rule.cpp, test/unit/params_ref.cpp
query_rule broke a grammar parse invariant by using different interpretations of the string depending on whether the reason for termination was the end of a string or a continuation with an invalid character.
fix #864
=> refactor: query_rule consistent interpretation

CMakeLists.txt
=> build: exceptions are not an explicit default

README.adoc, include/boost/url/url_base.hpp, src/url_base.cpp, test/unit/url_view.cpp
The copy operation from a url_view_base should use the pointed implementation rather than the underlying implementation so that url_views that refer to other urls are accounted for.
fix #872
=> refactor(url_base): copy operation uses reference to underlying implementation

doc/build_antora.sh
Running `build_antora.sh` in CI jobs there is no way of ascertaining if it failed since the last command is
`echo "Done"`
which always returns 0.    A solution could be to move `npx antora` as the last command, so its exit code will be the same as the script itself.   Or enable the bash setting "Exit immediately if a command exits with a non-zero status."
=> docs: set -e

doc/.gitignore, doc/html/index.html, doc/index.html
Documentation is in boost/doc/antora/url/index.html, but any user who visits the entry point of the a previous version in boost/libs/url/doc/html/index.html would get a 404.
fix #878
=> docs: redirects from doc/html

include/boost/url/grammar/string_view_base.hpp
Since https://github.com/boostorg/core/commit/92f6cfb3ccf977b6a5c615ce174a9d94002b3b0d in Boost.Core, we have been getting "error: use of undeclared identifier 'hash_value'" because hash_value is not part of the interface of core::string_view.
hash_value has been removed from core::string_view because it's redundant. Boost containers don't need it and it does not enable std containers.
=> refactor(string_view_base): remove hash_value

.github/workflows/ci.yml
* Support ubuntu noble and clang 19
* Support tags without conventional commits for changelog
* Better handling of multi-config generators
* boost-clone initializes essential modules
* Multiple bug fixes
=> ci: cpp-actions v1.8.8

.github/workflows/ci.yml, include/boost/url/detail/any_params_iter.hpp, include/boost/url/detail/url_impl.hpp, include/boost/url/encode.hpp, include/boost/url/encoding_opts.hpp, include/boost/url/impl/encode.hpp, include/boost/url/impl/params_ref.hpp, include/boost/url/param.hpp, include/boost/url/params_base.hpp, include/boost/url/url_base.hpp, src/detail/any_params_iter.cpp, src/detail/normalize.cpp, src/detail/normalize.hpp, src/params_base.cpp, src/params_encoded_ref.cpp, src/params_encoded_view.cpp, src/params_ref.cpp, src/rfc/detail/charsets.hpp, src/url_base.cpp, src/url_view_base.cpp, test/unit/encode.cpp, test/unit/params_ref.cpp
This commit refactors all functions so they have consistent behavior for the space-as-plus encoding option.
- any_params_iter objects store and apply the appropriate option when measuring and copying
- when the option is enabled, encoding functions encode space-as-plus and plus as %2B regardless of the charset
- normalization and comparison algorithms take into consideration special query chars whose meaning changes depending on encoding
- all params_view objects created with default options enable space-as-plus encoding
fix #903
=> fix: consistent behavior for space-as-plus option

example/router/impl/router.hpp, example/router/router.hpp, include/boost/url/authority_view.hpp, include/boost/url/decode_view.hpp, include/boost/url/detail/config.hpp, include/boost/url/encode.hpp, include/boost/url/error_types.hpp, include/boost/url/grammar/all_chars.hpp, include/boost/url/grammar/alnum_chars.hpp, include/boost/url/grammar/alpha_chars.hpp, include/boost/url/grammar/dec_octet_rule.hpp, include/boost/url/grammar/digit_chars.hpp, include/boost/url/grammar/hexdig_chars.hpp, include/boost/url/grammar/unsigned_rule.hpp, include/boost/url/grammar/vchars.hpp, include/boost/url/ipv6_address.hpp, include/boost/url/params_encoded_base.hpp, include/boost/url/rfc/authority_rule.hpp, include/boost/url/rfc/ipv4_address_rule.hpp, include/boost/url/rfc/ipv6_address_rule.hpp, include/boost/url/rfc/pct_encoded_rule.hpp, include/boost/url/rfc/query_rule.hpp, include/boost/url/rfc/relative_ref_rule.hpp, include/boost/url/rfc/uri_reference_rule.hpp, include/boost/url/rfc/uri_rule.hpp, include/boost/url/segments_base.hpp, include/boost/url/segments_encoded_base.hpp, include/boost/url/url_base.hpp, src/rfc/query_rule.cpp
This commit removes comments in the Doxygen documentation format from source files. This documentation format was there in a transition stage where we supported both Doxygen and MrDocs.
We only leave documentation in the MrDocs format now. This means the `BOOST_URL_DOCS` macro is no longer necessary: symbols are documented where they are defined instead of fake implementation defined symbols.
=> docs: no Doxygen documentation variant
